version: '3.5'
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gorm
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - backend-bridge

  redis:
    container_name: redis
    image: redis:latest
    ports:
    - "6379:6379"
    networks:
      - backend-bridge
    restart: always
    
  znews:
    container_name: znews
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
    command: ./main
    restart: always
    networks:
      - backend-bridge
    depends_on:
      - db
      - redis
    volumes:
    - ./logs/:/usr/local/go/src/znews/logs

networks:
  backend-bridge:
    driver: bridge

