definitions:
  model.Login:
    properties:
      account:
        example: kevin
        type: string
      password:
        example: "123456"
        type: string
    type: object
  model.RegisterStep1:
    properties:
      account:
        example: kevin
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: kevin
  description: Gin swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin swagger
  version: 1.8.10
paths:
  /member/login:
    post:
      parameters:
      - description: 登入成功回傳 token
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/model.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 登入
      tags:
      - user
  /member/registerStep1:
    post:
      parameters:
      - description: 檢查帳號是否已存在
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.RegisterStep1'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: 註冊 Step1
      tags:
      - user
  /v1/users/{id}:
    get:
      parameters:
      - default: 1
        description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
