definitions:
  model.CreateCase:
    properties:
      account:
        example: kevin@gmail.com
        type: string
      cityTalk:
        example: "04"
        type: string
      cityTalk2:
        example: "26232356"
        type: string
      contactTime:
        example: m,a
        type: string
      email:
        example: kevin@gmail.com
        type: string
      expectDate:
        example: 2022/02/02
        type: string
      expectDateChk:
        example: "1"
        type: string
      expectMoney:
        example: "5000"
        type: string
      extension:
        example: "0000"
        type: string
      filesName:
        example:
        - '[a.jpg]'
        items:
          type: string
        type: array
      kind:
        example: o:一般案件 i:急件
        type: string
      line:
        example: imlineid
        type: string
      name:
        example: kevin
        type: string
      phone:
        example: "0999999999"
        type: string
      title:
        example: 電傷平台架設
        type: string
      type:
        example: 程式開發
        type: string
      workArea:
        example: 台北市 信義區
        type: string
      workAreaChk:
        example: "1"
        type: string
      workContent:
        example: 電傷平台架設，伺服器維護...
        type: string
    type: object
  model.Login:
    properties:
      account:
        example: kevin@gmail.com
        type: string
      password:
        example: "123456"
        type: string
    type: object
  model.ProfileSave:
    properties:
      account:
        example: kevin@gmail.com
        type: string
      introduction:
        example: 我有 8000 名部下
        type: string
      name:
        example: 桐谷和人
        type: string
      oldPassword:
        example: "123456"
        type: string
      password:
        example: "123456"
        type: string
      phone:
        example: "0999999999"
        type: string
      pwdSwitch:
        example: true
        type: boolean
      zipcode:
        example: "200"
        type: string
    type: object
  model.RegisterStep1:
    properties:
      email:
        example: kevin@gmail.com
        type: string
    type: object
  model.RegisterStep3:
    properties:
      account:
        example: kevin@gmail.com
        type: string
      email:
        example: kevin@gmail.com
        type: string
      introduction:
        example: 我有 8000 名部下
        type: string
      name:
        example: 桐谷和人
        type: string
      password:
        example: "123456"
        type: string
      phone:
        example: "0999999999"
        type: string
      zipcode:
        example: "200"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: kevin
  description: Gin swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin swagger
  version: 1.8.10
paths:
  /case/create:
    post:
      parameters:
      - description: 發案
        in: body
        name: case
        required: true
        schema:
          $ref: '#/definitions/model.CreateCase'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: 發案/案件建立
      tags:
      - case
  /case/getAll:
    get:
      parameters:
      - description: 接案查詢
        in: path
        name: case
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: 接案查詢
      tags:
      - case
  /case/getDetail/{caseid}:
    get:
      parameters:
      - description: 案件詳細資料
        in: path
        name: case
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: 案件詳細資料
      tags:
      - case
  /download/{filename}:
    get:
      parameters:
      - description: 下載檔案
        in: path
        name: files
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: 下載檔案
      tags:
      - file
  /member/login:
    post:
      parameters:
      - description: 登入成功回傳 token
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/model.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 登入
      tags:
      - user
  /member/profile/{id}:
    get:
      parameters:
      - default: ”
        description: 帳號
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: GetProfile
      tags:
      - user
  /member/registerStep1:
    post:
      parameters:
      - description: 檢查帳號是否已存在
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.RegisterStep1'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: 註冊 Step1
      tags:
      - user
  /member/registerStep3:
    post:
      parameters:
      - description: 註冊帳號
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.RegisterStep3'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: 註冊 Step3
      tags:
      - user
  /profile/save:
    post:
      parameters:
      - description: 修改成功回傳 boolean
        in: body
        name: MyAccount
        required: true
        schema:
          $ref: '#/definitions/model.ProfileSave'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: 個人資料儲存
      tags:
      - user
  /upload:
    post:
      parameters:
      - description: 上傳檔案
        in: formData
        items:
          type: string
        name: files
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: 上傳檔案
      tags:
      - file
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
